dist: xenial
language: python
python:
- '3.7'
install: true
script: true
deploy:
  provider: pypi
  user: gluonts
  password:
    secure: Wbor4gG9MEDSLuuTPa9+ECgNo5Bq6YteFZ5ZFJAH7LcGzS77R1TiT1YiIbLcOVASdZKggR0+WF0rbK+vv1leKmcYWSv9EzuWqOJtb2q6Q6mMyYM23JXj0QtkZBd2LR7oaaVG5V2l/+C+FfduZsZiMF4/KYZb37H94L999yvf7QN9btwtKYFCDFs7DFkyvIG6/xiJ9SN1J5bdKPHVQdoOF5m177ConfNmTAx8qSR7w+RVBqdBkPp3UENmlqXTQySDJb/1QG4ES5upAhtMoDRIXfpaHVXep9fjmDW2moOGXiO2J49Qh1FzSibM7SVV6j6TSApic+HFHj5uf7ltHnH/grL1sxuieGvd46nWUezb3L9/w/bpPWfAw9KXVUjSOAq/LhHkGp0vpwqGxAMtMhMqb12o9nIjsnM2M/W0iicWP6/qGjF0l4vzm3dbtW1I7NFayWSKNanR31RY6W/i04wDogHgu3CSxKKCZ1G7+bO72kdYKMpH5paHI1BJ7O5XnnhFuHU2455My2oIPSTK6uHQyXLR1UsTgHxphHxquXVE6fbjf1mzVYpvpLooOvgRNoVmTZhJVb6xnOnOb5NTqqk4L1iOM1cSk+ovtJiePpg1RuIROi5LOR1QNHNwjqXWkaEqPnPBrp8xlPOmwYcLwJAi82rsDqF0oIabN5tKmEACXJQ=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
